// commit-msg hook (L5/AI-attribution) + install-git-hooks.sh chained-original
// tests. Split out of test/git-hooks.test.ts (2026-09-08) so the hook suites
// run as several files in parallel under node --test; shared hermetic
// fixtures live in test/helpers/hook-fixtures.ts.
import { test, after } from "node:test";
import assert from "node:assert/strict";
import { spawnSync, execFileSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { ROOT, COMMIT_MSG, INSTALL_HOOKS, makeDir, cleanupTempDirs } from "./helpers/hook-fixtures.ts";
import { neutraliseHostGitConfig } from "./helpers/git.ts";

// Process-wide hermetic git (the shared fixtures neutralise too, but the
// hermetic-git guard requires the call to appear in THIS file's code).
neutraliseHostGitConfig();

after(cleanupTempDirs);

// ---------------------------------------------------------------------------
// commit-msg (PR #7 lesson 8)
// ---------------------------------------------------------------------------

function runCommitMsg(message: string, env: Record<string, string> = {}) {
  const dir = makeDir();
  const msgFile = join(dir, "COMMIT_EDITMSG");
  writeFileSync(msgFile, message);
  return spawnSync("bash", [COMMIT_MSG, msgFile], { encoding: "utf8", env: { ...process.env, ...env } });
}

test("plain conventional commit passes", () => {
  assert.equal(runCommitMsg("feat: add gate\n\nDetails.").status, 0);
});

test("FP regression: 'Generated by the maintainer' passes", () => {
  assert.equal(runCommitMsg("docs: x\n\nGenerated by the maintainer script.").status, 0);
});

test("FP regression: 'Generated by domain tooling' passes", () => {
  assert.equal(runCommitMsg("chore: x\n\nGenerated by domain tooling.").status, 0);
});

test("'Generated by AI' blocked", () => {
  assert.notEqual(runCommitMsg("feat: x\n\nGenerated by AI assistant").status, 0);
});

test("'Generated with ChatGPT' blocked (unbounded GPT)", () => {
  assert.notEqual(runCommitMsg("feat: x\n\nGenerated with ChatGPT").status, 0);
});

test("Co-Authored-By Claude blocked", () => {
  assert.notEqual(runCommitMsg("fix: y\n\nCo-Authored-By: Claude <noreply@anthropic.com>").status, 0);
});

test("robot emoji + Claude blocked", () => {
  assert.notEqual(runCommitMsg("feat: z\n\n🤖 Generated with Claude Code").status, 0);
});

test("bypass env allows AI attribution through commit-msg", () => {
  assert.equal(runCommitMsg("feat: x\n\nGenerated by AI", { REVIEW_GATE_BYPASS: "1" }).status, 0);
});

// ---------------------------------------------------------------------------
// install-git-hooks.sh: chained-original preservation across re-installs
// ---------------------------------------------------------------------------

test("P1: re-install preserves a chained original hook (incl. a path with spaces)", () => {
  // Repo whose .git dir lives under a path containing a space — the old
  // extraction (`tr -d '\" '`) destroyed such paths on re-install.
  const base = makeDir();
  const dir = join(base, "my repo");
  mkdirSync(dir, { recursive: true });
  execFileSync("git", ["init"], { cwd: dir, stdio: "ignore" });
  execFileSync("git", ["-c", "user.name=t", "-c", "user.email=t@t", "commit", "--allow-empty", "-m", "init"], { cwd: dir, stdio: "ignore" });
  // Pre-existing user hook that must survive two installer runs.
  const hooksDir = join(dir, ".git", "hooks");
  mkdirSync(hooksDir, { recursive: true });
  const sentinel = join(dir, "original-ran");
  writeFileSync(join(hooksDir, "pre-commit"), `#!/usr/bin/env bash\ntouch "${sentinel}"\n`, { mode: 0o755 });

  const first = spawnSync("bash", [INSTALL_HOOKS], { cwd: dir, encoding: "utf8" });
  assert.equal(first.status, 0, first.stderr);
  const second = spawnSync("bash", [INSTALL_HOOKS], { cwd: dir, encoding: "utf8" });
  assert.equal(second.status, 0, second.stderr);

  // After re-install the chain must still reference the backed-up original.
  const hook = readFileSync(join(hooksDir, "pre-commit"), "utf8");
  assert.match(hook, /pre-pi-review-gate/, "chained original lost on re-install");
  // Running the chained hook executes the original (sidecar absent → gate allows).
  const run = spawnSync("bash", [join(hooksDir, "pre-commit")], { cwd: dir, encoding: "utf8" });
  assert.equal(run.status, 0, run.stderr);
  assert.ok(existsSync(sentinel), "original hook did not run through the chain");
});
