/**
 * Agent-file FRONTMATTER surgery — read the model chain out of an `agents/*.md`
 * frontmatter and write a new one in, keeping the generated marker.
 *
 * Split out of lib/model-config.ts (the config layer that decides WHAT to
 * render); this module only knows the file format.
 */

/** Marker line placed at the top of a generated frontmatter so render products
 *  can be recognized and only generated files are ever deleted/restored.
 *  Sits on a line that does not match a `key:` pattern, so the frontmatter
 *  parser ignores it. */
export const GENERATED_MARKER = "# @generated by pi-review-gate models";

// ---------------------------------------------------------------------------
// Frontmatter rendering (model/fallbackModels replacement, marker preserved)
// ---------------------------------------------------------------------------

export interface AgentFrontmatterEdit {
  model: string;
  fallbackModels: string[];
}

/** True when the agent file carries the generated marker (render product). */
export function isGeneratedAgentFile(text: string): boolean {
  return text
    .split(/\r?\n/, 8)
    // EXACT marker, or the retired editor's render variant (marker + a
    // SPACE + suffix) — the empty-boundary prefix keeps those files managed
    // while a longer CONCATENATED continuation such as "# @generated by
    // pi-review-gate models-other" stays a foreign tool's marker (round-2
    // P1: a broader prefix once let the cleanup delete files other tools
    // owned; round-11 P1: models-other/modelsX were still misrecognized).
    .some((l) => {
      const t = l.trim();
      return t === GENERATED_MARKER || t.startsWith(`${GENERATED_MARKER} `);
    });
}

/**
 * Replace the `model` / `fallbackModels` lines of a `---` frontmatter, keeping
 * every other FIELD and the body untouched. Inserts the generated marker when
 * `mark` is true (idempotent). Returns `undefined` when the text has no
 * frontmatter block (caller treats it as an error case upstream).
 *
 * Frontmatter BLANK LINES are not preserved: removing the old `model:` /
 * `fallbackModels:` lines leaves holes, and the renderer drops every blank
 * frontmatter line rather than trying to tell a hole from an intentional gap.
 * Consequence, accepted: a paragraph break inside a hand-written folded/literal
 * block scalar is folded away in the rendered copy. No agent file this package
 * ships is affected, and a hand-written file is backed up to `<name>.md.bak`
 * before the renderer ever takes it over, so the original is recoverable.
 */
export function replaceFrontmatterModels(
  text: string,
  edit: AgentFrontmatterEdit,
  mark = true,
): string | undefined {
  // The opener must agree with frontmatterBlock — the single delimiter
  // authority, a literal port of the runtime parser — which opens a block on
  // ANY `---…` first line (`startsWith("---")`). A stricter opener here
  // refuses to RENDER a file the runtime really LOADS, so explicit slots are
  // dropped while the stale chain keeps deploying: `^---\n` rejected `--- `
  // (round-2 P1) and `---[ \t]*` still rejected `--- # note` / `---x`
  // (round-3 P2). `[^\n]*` therefore takes the WHOLE opener line, kept verbatim
  // in `open` so the render stays byte-faithful.
  // Residual, deliberate: an EMPTY block (`---\n---`) shares one newline between
  // opener and close, which this regex cannot split, so it returns undefined
  // here while frontmatterBlock reports "". What keeps that off the render path
  // is readBase(): the base is the package's OWN upstream agent file (all
  // KNOWN_AGENTS carry a `model:` line), and a hand-written target is backed up
  // to <name>.md.bak first. Only a BROKEN install (upstream missing) combined
  // with a hand-written empty frontmatter reaches it, and then the caller
  // reports "frontmatter parse failed" and skips the file — fail-soft, but the
  // message names the wrong cause. Widening the CLOSE to `\r?\n?---` would fix
  // the split and produce `model: x---` on rebuild (no separating newline), so
  // the split, not the message, is what would have to be rewritten.
  const m = /^(---[^\n]*\r?\n)([\s\S]*?)(\r?\n---)/.exec(text);
  if (!m) return undefined;
  const [, open, blockRaw, close] = m;
  // Drop the `model`/`fallbackModels` key AND any block-list continuation
  // lines that hang under them (`  - item`), so a YAML block fallback list is
  // never left as orphaned bullets in the rendered frontmatter. A blank or
  // comment line between the key and its bullets must not terminate the
  // match early (round-11 P1: `fallbackModels:` + blank line + bullets left
  // orphaned `  - a` lines that the YAML parser re-attached to a previous key),
  // and a FOLLOWING key's own block list must not be swallowed either: the
  // continuation accepts ONLY bullet / comment / blank lines, never a
  // `tools:`-style empty-valued key (round-11 P1: cross-key bleed).
  const block = blockRaw.replace(/^(model|fallbackModels):[^\n]*(?:\n[ \t]*(?:-[^\n]*|#[^\n]*|$))*$/gm, "");
  const lines = block.split("\n");
  const already = isGeneratedAgentFile(text);
  const out: string[] = [];
  if (mark && !already) out.push(GENERATED_MARKER);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue; // drop stale blank lines introduced by removal
    out.push(line); // existing marker lines are preserved verbatim
  }
  out.push(`model: ${edit.model}`);
  if (edit.fallbackModels.length > 0) out.push(`fallbackModels: ${edit.fallbackModels.join(", ")}`);
  return `${open}${out.join("\n")}${close}${text.slice(m[0]!.length)}`;
}

/**
 * Fold a YAML folded (`>` / `>-`) block scalar the way the agent-file loader
 * does (this parser was a literal port of the pi-subagents one, kept because
 * the semantics are the ones on disk):
 * blank lines are PARAGRAPH separators that survive as newlines, and a
 * more-indented line keeps its own line break. A plain
 * `replace(/\n[ \t]*\/g, " ")` collapsed both into single spaces, so a folded
 * value parsed here did not match the value the runtime actually loads.
 */
function foldBlock(block: string): string {
  let folded = "";
  let hasContent = false;
  let previousIsMoreIndented = false;
  let blankLines = 0;
  for (const line of block.split("\n")) {
    const current = line.trimEnd();
    if (current.trim() === "") {
      if (hasContent) blankLines++;
      continue;
    }
    const currentIsMoreIndented = current.length > current.trimStart().length;
    if (hasContent) {
      if (blankLines > 0) {
        folded += "\n".repeat(blankLines + (previousIsMoreIndented || currentIsMoreIndented ? 1 : 0));
      } else {
        folded += previousIsMoreIndented || currentIsMoreIndented ? "\n" : " ";
      }
    }
    folded += current;
    hasContent = true;
    previousIsMoreIndented = currentIsMoreIndented;
    blankLines = 0;
  }
  return folded.trim();
}

/**
 * The frontmatter BLOCK of an agent file (between the delimiters), or
 * undefined when the loader would not see a frontmatter block at all.
 * The single delimiter authority for this package — see the body for why.
 */
export function frontmatterBlock(text: string): string | undefined {
  const normalized = text.replace(/\r\n/g, "\n");
  // Delimiter handling is a LITERAL port of the agent-file parser's
  // `parseFrontmatter` rather than a
  // regex approximation of it: the runtime only checks `startsWith("---")` and
  // then `indexOf("\n---", 3)`, so `--- `, `---\t` and even `---anything` all
  // OPEN a frontmatter block. A stricter `^---\n` reported such a file as NOT
  // loadable while it really does shadow the global agent — the very
  // divergence class this reference parser exists to eliminate. The `slice(4)`
  // (not "slice past the first newline") is upstream's too, and dropping the
  // rest of that first line is exactly what the runtime does.
  //
  // EVERY frontmatter consumer in this package goes through here (the doctor's
  // pre-check, model-diagnose, the widget), so "the runtime loads it" and "we
  // can diagnose it" can never disagree: a lenient identity check paired with
  // a strict diagnosis gate made an overriding project agent shadow the global
  // entry AND then be skipped, so a dead live chain reported PASS.
  if (!normalized.startsWith("---")) return undefined;
  const endIndex = normalized.indexOf("\n---", 3);
  if (endIndex === -1) return undefined;
  return normalized.slice(4, endIndex);
}

/**
 * Parse `---` frontmatter with the semantics the agent-file loader uses
 * (the parser below is a literal port of the pi-subagents one it was written
 * to stay in step with, kept as-is because the FILES did not change): top-level `key: value` lines only (indented lines belong
 * to a preceding block scalar), `>`, `>-`, `|`, `|-` block scalars collect
 * their indented continuation lines (folded/literal), and quoted scalars are
 * unquoted. Returns a map of top-level fields; keys absent from the file are
 * missing from the map. This is the loadable-check reference for project
 * agent files — a regex approximation kept diverging from the runtime
 * (round-11 P1: block scalars, nested keys, quoted empties).
 */
export function parseAgentFrontmatterFields(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  const block = frontmatterBlock(text);
  if (block === undefined) return out;
  const lines = block.split("\n");
  let currentKey: string | null = null;
  let currentIndent: number | null = null;
  let currentLines: string[] | null = null;
  let currentFolded = false;
  // LITERAL blocks (`|` / `|-`) admit blank continuation lines just like folded
  // ones — the agent-file parser gates on `(currentFolded ||
  // currentLiteral) && trimmed === ""`. Tracking only `folded` truncated a literal block at its
  // first blank line (and emptied one that STARTS blank), so
  // projectAgentIdentity reported a runtime-loadable project agent as not
  // loadable and the shadow detection silently missed it.
  let currentLiteral = false;
  const flush = (): void => {
    if (currentKey === null || currentLines === null) return;
    const raw = currentLines.join("\n");
    const prefix = raw.match(/^[ \t]+(?=\S)/m)?.[0] ?? "";
    const stripped = prefix
      ? raw
          .replace(new RegExp(`^${prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`, "gm"), "")
          .replace(/^\n/, "")
      : raw;
    if (currentFolded) {
      out[currentKey] = foldBlock(stripped);
    } else {
      out[currentKey] = stripped;
    }
    currentKey = null;
    currentLines = null;
    currentIndent = null;
    currentFolded = false;
    currentLiteral = false;
  };
  for (const line of lines) {
    const indent = line.search(/\S|$/);
    if (currentKey !== null && currentLines !== null && (indent > (currentIndent ?? 0) || ((currentFolded || currentLiteral) && line.trim() === ""))) {
      currentLines.push(line);
      continue;
    }
    flush();
    const kv = /^([\w-]+):\s*(.*)$/.exec(line);
    if (!kv) continue;
    const key = kv[1]!;
    const raw = kv[2]!.trim();
    const isQuoted =
      (raw.startsWith('"') && raw.endsWith('"')) || (raw.startsWith("'") && raw.endsWith("'"));
    // Upstream decides on the UNQUOTED value (`value === "" || isFolded ||
    // isLiteral`), so `key: ""` OPENS a block there and collects the indented
    // lines that follow. Deciding on the RAW text made a quoted empty a
    // terminal scalar here — the same parser-parity gap as the delimiter and
    // block-scalar ones. A quoted empty with nothing indented after it still
    // yields "", so the common case is unchanged.
    const value = isQuoted ? raw.slice(1, -1) : raw;
    const isFolded = !isQuoted && (raw === ">" || raw === ">-");
    const isLiteral = !isQuoted && (raw === "|" || raw === "|-");
    if (value === "" || isFolded || isLiteral) {
      currentKey = key;
      currentIndent = indent;
      currentLines = [];
      currentFolded = isFolded;
      currentLiteral = isLiteral;
    } else {
      out[key] = value;
    }
  }
  flush();
  return out;
}

/**
 * The loadability check for a project agent file: both
 * `name` and `description` must be non-empty AFTER parsing; the agent is
 * registered under frontmatter `name` (the file basename is irrelevant — a
 * `custom.md` carrying `name: reviewer` DOES shadow the global reviewer).
 */
export function projectAgentIdentity(text: string): string | undefined {
  const fields = parseAgentFrontmatterFields(text);
  const name = fields.name?.trim();
  const desc = fields.description?.trim();
  return name && desc ? name : undefined;
}
/**
 * Extract the (default) model chain currently pinned in a file's frontmatter —
 * used to render an EXPLICIT auto:true as a "default-chain overlay" that
 * shadows a lower layer's slot render. `undefined` when the file has no
 * parseable frontmatter model (the caller treats it as an error).
 */
export function extractFrontmatterChain(
  text: string,
): { model: string; fallback: string[] } | undefined {
  // Same opener as replaceFrontmatterModels, for the same reason: the runtime
  // parser (and frontmatterBlock, its literal port) opens a block on ANY `---…`
  // first line, so this reader must not refuse a file they accept — an
  // `auto:true` overlay would then report "no parseable frontmatter" for a file
  // that really deploys. Same deliberate residual: an EMPTY block is not split.
  const m = /^---[^\n]*\r?\n([\s\S]*?)\r?\n---/.exec(text);
  if (!m) return undefined;
  const fm = m[1]!;
  const model = /^model:\s*(.+?)\s*$/m.exec(fm)?.[1];
  if (!model) return undefined;
  // fallbackModels can be inline (`a, b`) OR a YAML block list (`\n  - a`).
  // NOTE: `[ \t]*` — `\s` would cross the newline and swallow the first block
  // bullet, making the block-list branch below unreachable (round-8 P1).
  const fbHead = /^fallbackModels:[ \t]*([^\n]*)$/m.exec(fm)?.[1] ?? "";
  let fallback: string[] = [];
  if (fbHead.trim()) {
    fallback = fbHead.split(",").map((s) => s.trim()).filter(Boolean);
  } else if (fm.includes("fallbackModels:")) {
    // Block list: collect ONLY the indented `- item` lines that follow, and
    // STOP at the first non-bullet line — a later block-list key (tools:,
    // defaultReads:) must never leak its items into the default chain
    // (round-9 P2).
    const fromIdx = fm.indexOf("fallbackModels:") + "fallbackModels:".length;
    fallback = [];
    for (const raw of fm.slice(fromIdx).split("\n").slice(1)) {
      const t = raw.trim();
      if (t === "") continue;
      if (!/^-\s+/.test(t)) break;
      fallback.push(t.replace(/^-\s+/, "").trim());
    }
  }
  return { model: model.trim(), fallback };
}
