/**
 * pi-review-gate — per-agent model-chain configuration layer (agents section).
 *
 * WHY: the agent models used to be edited by hand in each `agents/*.md`
 * frontmatter. This module adds a config layer (`agents` section of
 * `.pi/review-gate.json` / `~/.pi/review-gate.json`, layered like precommit):
 *
 *   {
 *     "agents": {
 *       "reviewer": { "auto": false, "slots": ["onekey/gpt-5.6-sol:high", "claude-fable-5:max", "onekey/glm-5.3:high"] },
 *       "worker":   { "auto": false, "slots": ["opencode-go/deepseek-v4-flash:high"] }
 *     }
 *   }
 *
 * Semantics per configured agent:
 *   - NOT configured in this layer  → the renderer cleans up any generated
 *     copy this layer used to hold (back to the upstream default).
 *   - `auto: false` + slots          → `slots[0]` becomes the main model,
 *     `slots[1..]` the fallback chain, each entry keeping its own
 *     `:thinking` suffix (pi-subagents supports per-model thinking levels).
 *   - `auto: true` (explicit)        → the renderer writes a *default-chain
 *     overlay* (generated marker + the upstream default model chain). This
 *     lets a higher-precedence layer SHADOW a lower layer's slot render: with
 *     global `reviewer.auto:false` + slots, a project `reviewer.auto:true`
 *     must deploy the built-in default — not leave the global slots render in
 *     force (the deployed model would then contradict the effective config).
 *
 * Two layers, each rendered into its OWN agent directory (pi-subagents loads
 * both, project overriding user-global):
 *   - project layer → <project>/.pi/agents/*.md
 *   - global  layer → ~/.pi/agent/agents/*.md
 *
 * The extension and the installer call `applyAgentConfigLayer`;
 * `install-package.mjs` applies ONLY the global layer after copying (its
 * cwd is not trustworthy).
 *
 * Fail-safe: a missing/corrupt section, an unresolvable spec or an
 * incompatible thinking level NEVER loosens the gate — validation fails the
 * write and keeps the previous file.
 */

import { copyFileSync, existsSync, mkdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/** Max slots an agent may configure; longer lists are truncated with a diagnostic. */
export const MAX_SLOTS = 4;

/** Marker line placed at the top of a generated frontmatter so render products
 *  can be recognized and only generated files are ever deleted/restored.
 *  Sits on a line that does not match a `key:` pattern, so pi-subagents'
 *  frontmatter parser ignores it. */
export const GENERATED_MARKER = "# @generated by pi-review-gate models";

/** The 12 agent files the package ships. */
export const KNOWN_AGENTS: readonly string[] = Object.freeze([
  "reviewer",
  "reviewer-readonly",
  "module-reviewer",
  "adviser",
  "arbiter",
  "worker",
  "worker-readonly",
  "fixer",
  "planner",
  "triage",
  "recon",
  "goal-auditor",
]);

/**
 * Locate the `agents/` directory INSIDE this package.
 *
 * We PROBE the layouts the package really ships under instead of trusting one
 * relative path — the same lesson `resolveTrustedRunner` (extensions/
 * review-gate.ts) had to learn: `<here>/../agents` resolves in the dev repo
 * but not in every install layout, and a self-heal riding an unresolvable
 * path fails SILENTLY, which is precisely how a bootstrap deadlock survives.
 *
 * Evaluated lazily at CALL time, never at module scope, and defensive about
 * `import.meta.url`: scripts/install-package.mjs imports this module as a
 * base64 DATA URL, where `fileURLToPath` throws. A module-level evaluation
 * would take the whole postinstall render down with it; null lets each caller
 * fall back to the sourceDir it already knows.
 *
 * `baseDir` exists so the PROBE ORDER itself is testable against temp dirs
 * (production callers pass nothing and get this module's own directory); it is
 * never a runtime override.
 */
export function resolvePackageAgentsDir(baseDir?: string): string | null {
  let here: string;
  if (baseDir !== undefined) here = baseDir;
  else {
    try { here = dirname(fileURLToPath(import.meta.url)); } catch { return null; }
  }
  const candidates = [
    join(here, "agents"),             // package root layout
    join(here, "..", "agents"),       // lib/ sibling (repo + published package)
    join(here, "..", "..", "agents"), // nested install layout
  ];
  for (const c of candidates) {
    // IDENTITY, not just existence: the third candidate reaches two levels up,
    // where an unrelated `agents/` directory can easily live (a monorepo
    // sibling, a user's own folder). Adopting one would feed foreign files to
    // BOTH the chain renderer and the self-heal copy, so a candidate only
    // counts when it actually holds this package's roles.
    try {
      if (existsSync(c) && statSync(c).isDirectory() && existsSync(join(c, "reviewer.md"))) return c;
    } catch { /* keep probing */ }
  }
  return null;
}

export interface EnsureAgentFilesResult {
  /** Agent names whose missing file was restored by this call. */
  copied: string[];
  /** Human-readable problems (never thrown — a session must not die on this). */
  problems: string[];
}

/**
 * Bootstrap self-heal: restore any KNOWN_AGENTS file that is MISSING from the
 * user's agents dir.
 *
 * Without it a newly shipped role only appears after the postinstall runs
 * again, and a role the gate REQUIRES (goal-auditor) would be undispatchable
 * until then — no audit, no goal approval, and in loop mode not even an edit:
 * a deadlock whose only exit is turning the gate off. Healing at session start
 * kills that class for every future role.
 *
 * Deliberately narrow: it only fills GAPS. An existing file (hand-written,
 * rendered, or user-edited) is never touched, so this cannot clobber a
 * configured chain — it just re-establishes the same ownership AGENTS.md
 * already declares for the installed copies.
 */
export function ensureAgentFilesPresent(opts: {
  sourceDir: string | null;
  targetDir: string;
  agents: readonly string[];
}): EnsureAgentFilesResult {
  const copied: string[] = [];
  const problems: string[] = [];
  if (!opts.sourceDir) {
    problems.push(
      "cannot locate the package agents directory (包内 agents 目录无法定位) — missing agent roles " +
      "cannot self-heal; reinstall the package to restore them",
    );
    return { copied, problems };
  }
  for (const name of opts.agents) {
    const target = join(opts.targetDir, `${name}.md`);
    const source = join(opts.sourceDir, `${name}.md`);
    try {
      if (existsSync(target)) continue; // idempotent: gaps only, never an overwrite
      if (!existsSync(source)) continue; // nothing to heal from
      mkdirSync(opts.targetDir, { recursive: true });
      copyFileSync(source, target);
      copied.push(name);
    } catch (e) {
      problems.push(`${name}: could not restore the missing agent file (${e instanceof Error ? e.message : String(e)})`);
    }
  }
  return { copied, problems };
}

// ---------------------------------------------------------------------------
// Model spec parsing: `provider/id:thinking` | `id:thinking` | `provider/id` | `id`
// ---------------------------------------------------------------------------

export interface ModelSpec {
  provider: string | null;
  id: string;
  thinking: string | null;
  raw: string;
}

/**
 * The thinking levels pi understands. Single source in lib/: shared by
 * splitThinkingSuffix / parseModelSpec here and bareModelId / specThinking in
 * lib/review-fanout.ts — an ollama-style letter tag (`qwen3:latest`) is NOT a
 * level and is never stripped or carried (round-6 P2: two diverging copies
 * made the fan-out and the renderer disagree about such ids).
 * Mirrors pi-subagents' level list.
 */
export const KNOWN_THINKING_LEVELS: ReadonlySet<string> = new Set(["off", "low", "medium", "high", "xhigh", "max", "minimal"]);

/**
 * Split a trailing `:level` off a spec — the level is a KNOWN thinking level
 * (off/low/…/max), never part of an id.
 */
export function splitThinkingSuffix(spec: string): { base: string; thinking: string | null } {
  const colonIdx = spec.lastIndexOf(":");
  if (colonIdx === -1) return { base: spec, thinking: null };
  const suffix = spec.slice(colonIdx + 1);
  if (!KNOWN_THINKING_LEVELS.has(suffix)) return { base: spec, thinking: null };
  return { base: spec.slice(0, colonIdx), thinking: suffix };
}

export function parseModelSpec(spec: string): ModelSpec {
  const raw = spec.trim();
  if (!raw) return { provider: null, id: "", thinking: null, raw };
  // CR/LF inside a spec is never legitimate — it would inject extra
  // frontmatter lines when the spec is rendered into an agent file
  // (round-11 P1: `p/m\ntools: bash`). Refuse at the parse boundary.
  if (/[\r\n]/.test(raw)) return { provider: null, id: "", thinking: null, raw };
  const { base, thinking } = splitThinkingSuffix(raw);
  // A LEADING slash (slash === 0) is malformed, not a provider split: it
  // must not silently drop the slash and pass as a provider-less id (that
  // accepted "/gpt-5.6-sol" wherever "gpt-5.6-sol" resolved). Keeping the
  // whole base as the id makes the registry lookup fail → validateSpec
  // refuses the write (fail-safe).
  const slash = base.indexOf("/");
  if (slash <= 0) return { provider: null, id: base.trim(), thinking, raw };
  return { provider: base.slice(0, slash).trim(), id: base.slice(slash + 1).trim(), thinking, raw };
}

/** Bare model id (no provider, no thinking). */
export function bareModelId(spec: string): string {
  return parseModelSpec(spec).id;
}

export function formatSpec(provider: string | null, id: string, thinking: string | null): string {
  const base = provider ? `${provider}/${id}` : id;
  return thinking ? `${base}:${thinking}` : base;
}

// ---------------------------------------------------------------------------
// Registry: what the launch layer can actually resolve.
// ---------------------------------------------------------------------------

export interface RegistryModelInfo {
  id: string;
  /** `false` means the provider exposes only the `off` thinking level. */
  reasoning?: boolean;
  /** thinking level → mapped level (null when the level is unsupported). */
  thinkingLevelMap: Record<string, string | null> | null | undefined;
}

export type ModelRegistry = Record<string, RegistryModelInfo[]>;

function readJsonIfExists(path: string): unknown {
  try {
    return existsSync(path) ? JSON.parse(readFileSync(path, "utf8")) : undefined;
  } catch {
    return undefined; // corrupt — registry degrades gracefully
  }
}

/** Merge models.json (hand-written) and models-store.json (provider cache). */
export function loadRegistry(home = homedir()): ModelRegistry {
  const registry: ModelRegistry = {};
  const ingest = (root: unknown) => {
    if (typeof root !== "object" || root === null) return;
    const providers = (root as Record<string, unknown>).providers ?? root;
    for (const [provider, value] of Object.entries(providers as Record<string, unknown>)) {
      if (typeof value !== "object" || value === null) continue;
      const models = (value as Record<string, unknown>).models;
      if (!Array.isArray(models)) continue;
      const list = (registry[provider] ??= []);
      for (const m of models) {
        if (typeof m !== "object" || m === null) continue;
        const entry = m as Record<string, unknown>;
        const id = entry.id;
        if (typeof id !== "string" || !id) continue;
        const tlm = entry.thinkingLevelMap;
        const thinkingLevelMap =
          typeof tlm === "object" && tlm !== null && !Array.isArray(tlm)
            ? Object.fromEntries(
                Object.entries(tlm).filter(([, mapped]) => mapped === null || typeof mapped === "string"),
              ) as Record<string, string | null>
            : undefined;
        const reasoning = typeof entry.reasoning === "boolean" ? entry.reasoning : undefined;
        const existing = list.find((e) => e.id === id);
        if (existing) {
          // The FIRST source still wins the entry, but a later one may carry
          // metadata the first one lacked. Dropping it outright made a
          // metadata-less models.json entry SHADOW the store's map, and "no
          // map" means `:max` is refused — so the renderer rejected a level
          // the registry actually proves supported. Fill gaps only; never
          // overwrite what the higher-priority source already stated.
          if (existing.thinkingLevelMap === undefined && thinkingLevelMap !== undefined) {
            existing.thinkingLevelMap = thinkingLevelMap;
          }
          if (existing.reasoning === undefined && reasoning !== undefined) {
            existing.reasoning = reasoning;
          }
          continue;
        }
        list.push({ id, reasoning, thinkingLevelMap });
      }
    }
  };
  ingest(readJsonIfExists(join(home, ".pi", "agent", "models.json")));
  ingest(readJsonIfExists(join(home, ".pi", "agent", "models-store.json")));
  return registry;
}

/**
 * All `provider/id:level` entries the registry proves supported for `spec`.
 * Missing metadata follows pi-subagents' defaults: every level except `max`
 * is allowed, while mapped null and unlisted `xhigh`/`max` are refused.
 */
export function supportedThinkingOptions(reg: ModelRegistry, spec: string): string[] {
  const { provider, id } = parseModelSpec(spec);
  const cands: Array<{ provider: string; info: RegistryModelInfo }> = [];
  if (provider) {
    for (const info of reg[provider] ?? []) if (info.id === id) cands.push({ provider, info });
  } else {
    for (const [p, models] of Object.entries(reg))
      for (const info of models) if (info.id === id) cands.push({ provider: p, info });
  }
  if (cands.length === 0) return [];
  const out = new Set<string>();
  for (const c of cands) {
    const tlm = c.info.thinkingLevelMap;
    if (c.info.reasoning === false) {
      out.add(`${c.provider}/${c.info.id}:off`);
      continue;
    }
    for (const level of KNOWN_THINKING_LEVELS) {
      const mapped = tlm?.[level];
      if (mapped === null || (mapped === undefined && level === "max")) continue;
      if (mapped === undefined && level === "xhigh" && tlm) continue;
      out.add(`${c.provider}/${c.info.id}:${level}`);
    }
  }
  return [...out].sort();
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

export interface SpecValidation {
  ok: boolean;
  /** Hard failure reason (write is refused). */
  reason?: string;
  /** Soft warning (write proceeds). */
  warning?: string;
}

/**
 * Validate one slot spec against the registry and launch allowlist.
 * Ambiguous provider-less ids and reasoning:false models are rejected for
 * unsupported thinking levels; opencode-go remains restricted to flash.
 */
export function validateSpec(reg: ModelRegistry, spec: string): SpecValidation {
  const parsed = parseModelSpec(spec);
  if (!parsed.id) return { ok: false, reason: `empty spec: "${spec}"` };

  const candidates: Array<{ provider: string; info: RegistryModelInfo }> = [];
  if (parsed.provider) {
    if (!reg[parsed.provider]) return { ok: false, reason: `provider not in the registry: "${parsed.provider}" (spec "${spec}")` };
    for (const info of reg[parsed.provider]) if (info.id === parsed.id) candidates.push({ provider: parsed.provider, info });
  } else {
    for (const [provider, models] of Object.entries(reg))
      for (const info of models) if (info.id === parsed.id) candidates.push({ provider, info });
    if (new Set(candidates.map((c) => c.provider)).size > 1) {
      return { ok: false, reason: `ambiguous model spec: "${spec}" exists under several providers — write it as provider/id` };
    }
  }
  if (candidates.length === 0) return { ok: false, reason: `model cannot be resolved: "${spec}" (absent from the registry)` };

  if (parsed.provider === "opencode-go" && parsed.id !== "deepseek-v4-flash") {
    return { ok: false, reason: `opencode-go only allows deepseek-v4-flash (cost allowlist), got "${spec}"` };
  }
  if (!parsed.provider && candidates.every((c) => c.provider === "opencode-go") && parsed.id !== "deepseek-v4-flash") {
    return { ok: false, reason: `opencode-go only allows deepseek-v4-flash, got "${spec}"` };
  }

  if (parsed.thinking) {
    const level = parsed.thinking;
    const supports = (info: RegistryModelInfo): boolean => {
      if (info.reasoning === false) return level === "off";
      const map = info.thinkingLevelMap;
      if (!map) return level !== "max";
      const mapped = map[level];
      if (mapped === null) return false;
      if ((level === "xhigh" || level === "max") && mapped === undefined) return false;
      return true;
    };
    if (!candidates.some(({ info }) => supports(info))) {
      const mapped = candidates
        .flatMap(({ info }) => Object.entries(info.thinkingLevelMap ?? {}))
        .filter(([, m]) => m !== null && m !== undefined)
        .map(([name]) => name)
        .sort();
      // A reasoning:false model DOES support one level — `off` — and nothing
      // else, but it carries no thinkingLevelMap, so the generic branch said
      // "supported: no metadata" and left the user with no idea what to pin.
      const allNonReasoning = candidates.every(({ info }) => info.reasoning === false);
      const supported = mapped.length > 0 ? mapped.join("/") : allNonReasoning ? "off" : "no metadata";
      return {
        ok: false,
        reason: `model ${parsed.provider ? parsed.provider + "/" : ""}${parsed.id} does not support thinking level "${level}" (supported: ${supported})`,
      };
    }
    if (candidates.every(({ info }) => !info.thinkingLevelMap && info.reasoning !== false)) {
      return { ok: true, warning: `model ${parsed.id} has no thinking-level metadata; level "${level}" is unverified (allowed)` };
    }
    return { ok: true };
  }
  return { ok: true };
}

/** Validate a whole slot list; first failure wins. */
export function validateSlots(reg: ModelRegistry, slots: readonly string[]): SpecValidation {
  for (const s of slots) {
    const v = validateSpec(reg, s);
    if (!v.ok) return v;
  }
  return { ok: true };
}

// ---------------------------------------------------------------------------
// agents config section parsing & layering
// ---------------------------------------------------------------------------

export interface AgentSlotSettings {
  auto: boolean;
  /** Effective slot chain (order = priority). Only honored when `auto` is false. */
  slots: string[];
  /** Which layer provided the settings. */
  source: "project" | "global" | "default";
  /** The entry was EXPLICITLY present but every field was invalid — the
   * renderer must keep the last good render instead of sweeping it (fail-safe). */
  malformed?: boolean;
}

export type AgentsConfigMap = Record<string, AgentSlotSettings>;

export interface ParseAgentsResult {
  /** Only the agents actually present in the section (auto-filled to defaults). */
  sections: Record<string, { auto?: boolean; slots?: string[]; malformed?: boolean }>;
  /** Human-readable diagnostics (truncation, unknown names). */
  diagnostics: string[];
}

/** Parse one `agents` section from a raw config file value. */
export function parseAgentsSection(
  raw: unknown,
  validNames: readonly string[] = KNOWN_AGENTS,
): ParseAgentsResult {
  const result: ParseAgentsResult = { sections: {}, diagnostics: [] };
  if (raw === undefined || raw === null) return result;
  if (typeof raw !== "object" || Array.isArray(raw)) {
    result.diagnostics.push("the agents section is not an object; ignored");
    return result;
  }
  for (const [name, value] of Object.entries(raw as Record<string, unknown>)) {
    if (!validNames.includes(name)) {
      result.diagnostics.push(`agents.${name} is not a known agent name; ignored`);
      continue;
    }
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      // A KNOWN agent whose entry is not an object (string/null/array) still
      // names the agent explicitly — dropping it would let the cleanup sweep
      // delete a previously valid render (round-11 P1: `{reviewer:"typo"}`
      // wiped the last good chain). Mark malformed → keep last render.
      result.diagnostics.push(`agents.${name} is not an object; ignored`);
      result.sections[name] = { malformed: true };
      continue;
    }
    const entry = value as Record<string, unknown>;
    const out: { auto?: boolean; slots?: string[] } = {};
    let autoInvalid = false;
    let slotsInvalid = false;
    if (entry.auto !== undefined && typeof entry.auto === "boolean") {
      out.auto = entry.auto;
    } else if (entry.auto !== undefined) {
      // A non-boolean auto (e.g. "false") would silently drop the whole
      // entry's meaning — say so instead of discarding it quietly. An
      // invalid `auto` also poisons otherwise-valid slots: defaulting to
      // auto:true would silently IGNORE the user's slot chain (round-11 P1).
      result.diagnostics.push(`agents.${name}.auto is not a boolean; ignored`);
      autoInvalid = true;
    }
    if (entry.slots !== undefined) {
      // A slot spec must never carry CR/LF: it would inject extra frontmatter
      // lines into the rendered agent file (round-11 P1: `p/m\ntools: bash`
      // passed validation and deployed a second `tools:` key).
      const clean = (s: unknown): s is string =>
        typeof s === "string" && s.trim().length > 0 && !/[\r\n]/.test(s);
      if (Array.isArray(entry.slots) && entry.slots.every(clean)) {
        const trimmed = entry.slots.map((s) => (s as string).trim()).filter(Boolean);
        if (trimmed.length > MAX_SLOTS) {
          result.diagnostics.push(`agents.${name}.slots has more than ${MAX_SLOTS} entries; truncated to the first ${MAX_SLOTS}`);
        }
        out.slots = trimmed.slice(0, MAX_SLOTS);
      } else {
        result.diagnostics.push(`agents.${name}.slots is not a non-empty array of strings; ignored`);
        // An INVALID slots key is not "no slots": rendering auto:false with
        // an empty slot list would silently replace the last good chain with
        // the built-in default (round-11 P1). Fail-safe: mark malformed.
        slotsInvalid = true;
      }
    }
    if (slotsInvalid || autoInvalid) {
      result.sections[name] = { malformed: true };
    } else if (out.auto !== undefined || out.slots !== undefined) {
      result.sections[name] = out;
    } else if (Object.keys(entry).length > 0) {
      // An entry with fields but NO valid one (e.g. `{slots:[1]}` or
      // `{auto:"false"}`) still names the agent EXPLICITLY — treating it
      // as absent would let the cleanup sweep delete a previously valid
      // render (round-11 P1: malformed entry wiped the last good chain).
      // Mark it malformed so the renderer keeps the last render. An EMPTY
      // object stays "absent": it is not a config and must not suppress
      // the reviewer-readonly follow (round-8 P2).
      result.sections[name] = { malformed: true };
    }
  }
  return result;
}

/**
 * Effective per-agent settings: project wins per agent, then global, then the
 * default (`auto: true`, empty slots). `source` records which layer decided,
 * so the UI can label it.
 */
export function effectiveAgentsConfig(
  globalRaw: unknown,
  projectRaw: unknown,
  validNames: readonly string[] = KNOWN_AGENTS,
): { map: AgentsConfigMap; diagnostics: string[] } {
  const map: AgentsConfigMap = {};
  const diagnostics: string[] = [];
  for (const name of validNames) map[name] = { auto: true, slots: [], source: "default" };

  const apply = (raw: unknown, source: "global" | "project") => {
    const parsed = parseAgentsSection(raw, validNames);
    diagnostics.push(...parsed.diagnostics);
    for (const [name, entry] of Object.entries(parsed.sections)) {
      if (!validNames.includes(name)) continue; // unknown agent names ignored
      if (entry.malformed) {
        // Explicitly present but field-invalid: keep whatever this layer
        // previously rendered — never treat it as "unconfigured" (the
        // cleanup would sweep a valid older render) nor render a default
        // chain over it (round-11 P1).
        map[name] = { auto: true, slots: [], source, malformed: true };
        continue;
      }
      map[name] = {
        auto: entry.auto ?? true,
        slots: entry.slots ?? [],
        source,
      };
    }
  };
  apply(globalRaw, "global");
  apply(projectRaw, "project");

  // auto:false with an EMPTY slot list still renders the default chain —
  // the fan-out treats it as the capability-ranked default path (an empty
  // slot list is never a silent no-review state), and the renderer writes
  // the default-chain overlay so this layer shadows any lower slot render.
  // Surface it so the deployed default is never a surprise.
  for (const name of validNames) {
    const e = map[name]!;
    if (e.source !== "default" && e.auto === false && e.slots.length === 0) {
      diagnostics.push(`${name}: auto:false with an empty slot list — rendering the built-in default chain (an empty slot list is never a silent no-review state)`);
    }
  }

  // reviewer-readonly follows reviewer's chain when reviewer is EXPLICITLY
  // configured (auto:false OR auto:true) and reviewer-readonly is not
  // configured on its own: the isolation-unavailable dispatch path
  // (prepare_review → reviewer-readonly) must run on the SAME effective chain.
  // Following auto:true to a higher layer also lets the project SHADOW a
  // global auto:false reviewer-readonly slot render.
  const rv = map.reviewer;
  const rr = map["reviewer-readonly"];
  if (rv && rv.source !== "default" && rr && rr.source === "default") {
    // Copy the slot ARRAY (deep), never share it: callers may mutate slots
    // in place, and sharing would silently edit reviewer's chain through
    // reviewer-readonly (and vice versa).
    map["reviewer-readonly"] = { ...rv, slots: [...rv.slots] };
  }
  return { map, diagnostics };
}

// ---------------------------------------------------------------------------
// Frontmatter rendering (model/fallbackModels replacement, marker preserved)
// ---------------------------------------------------------------------------

export interface AgentFrontmatterEdit {
  model: string;
  fallbackModels: string[];
}

/** True when the agent file carries the generated marker (render product). */
export function isGeneratedAgentFile(text: string): boolean {
  return text
    .split(/\r?\n/, 8)
    // EXACT marker, or the retired editor's render variant (marker + a
    // SPACE + suffix) — the empty-boundary prefix keeps those files managed
    // while a longer CONCATENATED continuation such as "# @generated by
    // pi-review-gate models-other" stays a foreign tool's marker (round-2
    // P1: a broader prefix once let the cleanup delete files other tools
    // owned; round-11 P1: models-other/modelsX were still misrecognized).
    .some((l) => {
      const t = l.trim();
      return t === GENERATED_MARKER || t.startsWith(`${GENERATED_MARKER} `);
    });
}

/**
 * Replace the `model` / `fallbackModels` lines of a `---` frontmatter, keeping
 * every other FIELD and the body untouched. Inserts the generated marker when
 * `mark` is true (idempotent). Returns `undefined` when the text has no
 * frontmatter block (caller treats it as an error case upstream).
 *
 * Frontmatter BLANK LINES are not preserved: removing the old `model:` /
 * `fallbackModels:` lines leaves holes, and the renderer drops every blank
 * frontmatter line rather than trying to tell a hole from an intentional gap.
 * Consequence, accepted: a paragraph break inside a hand-written folded/literal
 * block scalar is folded away in the rendered copy. No agent file this package
 * ships is affected, and a hand-written file is backed up to `<name>.md.bak`
 * before the renderer ever takes it over, so the original is recoverable.
 */
export function replaceFrontmatterModels(
  text: string,
  edit: AgentFrontmatterEdit,
  mark = true,
): string | undefined {
  // The opener must agree with frontmatterBlock — the single delimiter
  // authority, a literal port of the runtime parser — which opens a block on
  // ANY `---…` first line (`startsWith("---")`). A stricter opener here
  // refuses to RENDER a file the runtime really LOADS, so explicit slots are
  // dropped while the stale chain keeps deploying: `^---\n` rejected `--- `
  // (round-2 P1) and `---[ \t]*` still rejected `--- # note` / `---x`
  // (round-3 P2). `[^\n]*` therefore takes the WHOLE opener line, kept verbatim
  // in `open` so the render stays byte-faithful.
  // Residual, deliberate: an EMPTY block (`---\n---`) shares one newline between
  // opener and close, which this regex cannot split, so it returns undefined
  // here while frontmatterBlock reports "". What keeps that off the render path
  // is readBase(): the base is the package's OWN upstream agent file (all 12
  // KNOWN_AGENTS carry a `model:` line), and a hand-written target is backed up
  // to <name>.md.bak first. Only a BROKEN install (upstream missing) combined
  // with a hand-written empty frontmatter reaches it, and then the caller
  // reports "frontmatter parse failed" and skips the file — fail-soft, but the
  // message names the wrong cause. Widening the CLOSE to `\r?\n?---` would fix
  // the split and produce `model: x---` on rebuild (no separating newline), so
  // the split, not the message, is what would have to be rewritten.
  const m = /^(---[^\n]*\r?\n)([\s\S]*?)(\r?\n---)/.exec(text);
  if (!m) return undefined;
  const [, open, blockRaw, close] = m;
  // Drop the `model`/`fallbackModels` key AND any block-list continuation
  // lines that hang under them (`  - item`), so a YAML block fallback list is
  // never left as orphaned bullets in the rendered frontmatter. A blank or
  // comment line between the key and its bullets must not terminate the
  // match early (round-11 P1: `fallbackModels:` + blank line + bullets left
  // orphaned `  - a` lines that pi-subagents re-attached to a previous key),
  // and a FOLLOWING key's own block list must not be swallowed either: the
  // continuation accepts ONLY bullet / comment / blank lines, never a
  // `tools:`-style empty-valued key (round-11 P1: cross-key bleed).
  const block = blockRaw.replace(/^(model|fallbackModels):[^\n]*(?:\n[ \t]*(?:-[^\n]*|#[^\n]*|$))*$/gm, "");
  const lines = block.split("\n");
  const already = isGeneratedAgentFile(text);
  const out: string[] = [];
  if (mark && !already) out.push(GENERATED_MARKER);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue; // drop stale blank lines introduced by removal
    out.push(line); // existing marker lines are preserved verbatim
  }
  out.push(`model: ${edit.model}`);
  if (edit.fallbackModels.length > 0) out.push(`fallbackModels: ${edit.fallbackModels.join(", ")}`);
  return `${open}${out.join("\n")}${close}${text.slice(m[0]!.length)}`;
}

/**
 * Fold a YAML folded (`>` / `>-`) block scalar exactly the way pi-subagents
 * does (node_modules/pi-subagents/src/agents/frontmatter.ts `foldBlock`):
 * blank lines are PARAGRAPH separators that survive as newlines, and a
 * more-indented line keeps its own line break. A plain
 * `replace(/\n[ \t]*\/g, " ")` collapsed both into single spaces, so a folded
 * value parsed here did not match the value the runtime actually loads.
 */
function foldBlock(block: string): string {
  let folded = "";
  let hasContent = false;
  let previousIsMoreIndented = false;
  let blankLines = 0;
  for (const line of block.split("\n")) {
    const current = line.trimEnd();
    if (current.trim() === "") {
      if (hasContent) blankLines++;
      continue;
    }
    const currentIsMoreIndented = current.length > current.trimStart().length;
    if (hasContent) {
      if (blankLines > 0) {
        folded += "\n".repeat(blankLines + (previousIsMoreIndented || currentIsMoreIndented ? 1 : 0));
      } else {
        folded += previousIsMoreIndented || currentIsMoreIndented ? "\n" : " ";
      }
    }
    folded += current;
    hasContent = true;
    previousIsMoreIndented = currentIsMoreIndented;
    blankLines = 0;
  }
  return folded.trim();
}

/**
 * The frontmatter BLOCK of an agent file (between the delimiters), or
 * undefined when pi-subagents would not see a frontmatter block at all.
 * The single delimiter authority for this package — see the body for why.
 */
export function frontmatterBlock(text: string): string | undefined {
  const normalized = text.replace(/\r\n/g, "\n");
  // Delimiter handling is a LITERAL port of pi-subagents' parseFrontmatter
  // (node_modules/pi-subagents/src/agents/frontmatter.ts:65-79) rather than a
  // regex approximation of it: the runtime only checks `startsWith("---")` and
  // then `indexOf("\n---", 3)`, so `--- `, `---\t` and even `---anything` all
  // OPEN a frontmatter block. A stricter `^---\n` reported such a file as NOT
  // loadable while it really does shadow the global agent — the very
  // divergence class this reference parser exists to eliminate. The `slice(4)`
  // (not "slice past the first newline") is upstream's too, and dropping the
  // rest of that first line is exactly what the runtime does.
  //
  // EVERY frontmatter consumer in this package goes through here (the doctor's
  // pre-check, model-diagnose, the widget), so "the runtime loads it" and "we
  // can diagnose it" can never disagree: a lenient identity check paired with
  // a strict diagnosis gate made an overriding project agent shadow the global
  // entry AND then be skipped, so a dead live chain reported PASS.
  if (!normalized.startsWith("---")) return undefined;
  const endIndex = normalized.indexOf("\n---", 3);
  if (endIndex === -1) return undefined;
  return normalized.slice(4, endIndex);
}

/**
 * Parse `---` frontmatter with the SAME semantics pi-subagents uses
 * (frontmatter.ts): top-level `key: value` lines only (indented lines belong
 * to a preceding block scalar), `>`, `>-`, `|`, `|-` block scalars collect
 * their indented continuation lines (folded/literal), and quoted scalars are
 * unquoted. Returns a map of top-level fields; keys absent from the file are
 * missing from the map. This is the loadable-check reference for project
 * agent files — a regex approximation kept diverging from the runtime
 * (round-11 P1: block scalars, nested keys, quoted empties).
 */
export function parseAgentFrontmatterFields(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  const block = frontmatterBlock(text);
  if (block === undefined) return out;
  const lines = block.split("\n");
  let currentKey: string | null = null;
  let currentIndent: number | null = null;
  let currentLines: string[] | null = null;
  let currentFolded = false;
  // LITERAL blocks (`|` / `|-`) admit blank continuation lines just like folded
  // ones — pi-subagents' parseFrontmatter gates on `(currentFolded ||
  // currentLiteral) && trimmed === ""` (node_modules/pi-subagents/src/agents/
  // frontmatter.ts:92). Tracking only `folded` truncated a literal block at its
  // first blank line (and emptied one that STARTS blank), so
  // projectAgentIdentity reported a runtime-loadable project agent as not
  // loadable and the shadow detection silently missed it.
  let currentLiteral = false;
  const flush = (): void => {
    if (currentKey === null || currentLines === null) return;
    const raw = currentLines.join("\n");
    const prefix = raw.match(/^[ \t]+(?=\S)/m)?.[0] ?? "";
    const stripped = prefix
      ? raw
          .replace(new RegExp(`^${prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`, "gm"), "")
          .replace(/^\n/, "")
      : raw;
    if (currentFolded) {
      out[currentKey] = foldBlock(stripped);
    } else {
      out[currentKey] = stripped;
    }
    currentKey = null;
    currentLines = null;
    currentIndent = null;
    currentFolded = false;
    currentLiteral = false;
  };
  for (const line of lines) {
    const indent = line.search(/\S|$/);
    if (currentKey !== null && currentLines !== null && (indent > (currentIndent ?? 0) || ((currentFolded || currentLiteral) && line.trim() === ""))) {
      currentLines.push(line);
      continue;
    }
    flush();
    const kv = /^([\w-]+):\s*(.*)$/.exec(line);
    if (!kv) continue;
    const key = kv[1]!;
    const raw = kv[2]!.trim();
    const isQuoted =
      (raw.startsWith('"') && raw.endsWith('"')) || (raw.startsWith("'") && raw.endsWith("'"));
    // Upstream decides on the UNQUOTED value (`value === "" || isFolded ||
    // isLiteral`), so `key: ""` OPENS a block there and collects the indented
    // lines that follow. Deciding on the RAW text made a quoted empty a
    // terminal scalar here — the same parser-parity gap as the delimiter and
    // block-scalar ones. A quoted empty with nothing indented after it still
    // yields "", so the common case is unchanged.
    const value = isQuoted ? raw.slice(1, -1) : raw;
    const isFolded = !isQuoted && (raw === ">" || raw === ">-");
    const isLiteral = !isQuoted && (raw === "|" || raw === "|-");
    if (value === "" || isFolded || isLiteral) {
      currentKey = key;
      currentIndent = indent;
      currentLines = [];
      currentFolded = isFolded;
      currentLiteral = isLiteral;
    } else {
      out[key] = value;
    }
  }
  flush();
  return out;
}

/**
 * pi-subagents' loadable check for a project agent file (agents.ts): both
 * `name` and `description` must be non-empty AFTER parsing; the agent is
 * registered under frontmatter `name` (the file basename is irrelevant — a
 * `custom.md` carrying `name: reviewer` DOES shadow the global reviewer).
 */
export function projectAgentIdentity(text: string): string | undefined {
  const fields = parseAgentFrontmatterFields(text);
  const name = fields.name?.trim();
  const desc = fields.description?.trim();
  return name && desc ? name : undefined;
}
/**
 * Extract the (default) model chain currently pinned in a file's frontmatter —
 * used to render an EXPLICIT auto:true as a "default-chain overlay" that
 * shadows a lower layer's slot render. `undefined` when the file has no
 * parseable frontmatter model (the caller treats it as an error).
 */
export function extractFrontmatterChain(
  text: string,
): { model: string; fallback: string[] } | undefined {
  // Same opener as replaceFrontmatterModels, for the same reason: the runtime
  // parser (and frontmatterBlock, its literal port) opens a block on ANY `---…`
  // first line, so this reader must not refuse a file they accept — an
  // `auto:true` overlay would then report "no parseable frontmatter" for a file
  // that really deploys. Same deliberate residual: an EMPTY block is not split.
  const m = /^---[^\n]*\r?\n([\s\S]*?)\r?\n---/.exec(text);
  if (!m) return undefined;
  const fm = m[1]!;
  const model = /^model:\s*(.+?)\s*$/m.exec(fm)?.[1];
  if (!model) return undefined;
  // fallbackModels can be inline (`a, b`) OR a YAML block list (`\n  - a`).
  // NOTE: `[ \t]*` — `\s` would cross the newline and swallow the first block
  // bullet, making the block-list branch below unreachable (round-8 P1).
  const fbHead = /^fallbackModels:[ \t]*([^\n]*)$/m.exec(fm)?.[1] ?? "";
  let fallback: string[] = [];
  if (fbHead.trim()) {
    fallback = fbHead.split(",").map((s) => s.trim()).filter(Boolean);
  } else if (fm.includes("fallbackModels:")) {
    // Block list: collect ONLY the indented `- item` lines that follow, and
    // STOP at the first non-bullet line — a later block-list key (tools:,
    // defaultReads:) must never leak its items into the default chain
    // (round-9 P2).
    const fromIdx = fm.indexOf("fallbackModels:") + "fallbackModels:".length;
    fallback = [];
    for (const raw of fm.slice(fromIdx).split("\n").slice(1)) {
      const t = raw.trim();
      if (t === "") continue;
      if (!/^-\s+/.test(t)) break;
      fallback.push(t.replace(/^-\s+/, "").trim());
    }
  }
  return { model: model.trim(), fallback };
}

// ---------------------------------------------------------------------------
// Layer application (write/restore generated agent files)
// ---------------------------------------------------------------------------

export interface ApplyAgentLayerOptions {
  /** Effective per-agent settings (all known agents present). */
  agents: AgentsConfigMap;
  /** Rendering target directory (project .pi/agents or global ~/.pi/agent/agents). */
  targetDir: string;
  /** Upstream directory to copy a base file from when targetDir has none. */
  sourceDir: string;
  registry: ModelRegistry;
  /** Skip validation (used only by tests that want raw rendering). */
  validate?: boolean;
  /**
   * INFRASTRUCTURE layers (global ~/.pi/agent/agents; the postinstall copies
   * the defaults there) must RESTORE the upstream default when a config is
   * lifted — deleting the generated copy would leave no user-level agent file
   * at all until the next install. Optional layers (project .pi/agents) delete
   * instead (default).
   */
  restoreDefault?: boolean;
}

export interface ApplyAgentLayerResult {
  written: string[];
  deleted: string[];
  errors: string[];
  warnings: string[];
}

/**
 * Apply the effective config to ONE layer:
 *  - agent NOT configured in this layer → delete any generated product it used
 *    to hold (fall back to upstream), restoring a prior `.bak` if one exists;
 *  - `auto: false` + non-empty slots → validate, then render the slot chain;
 *  - explicit `auto: true` → render a *default-chain overlay* (marker + the
 *    upstream default model chain) so this layer SHADOWS a lower layer's slot
 *    render — deployed model always equals the effective config.
 * Never throws; every failure lands in `errors`.
 */
export function applyAgentConfigLayer(opts: ApplyAgentLayerOptions): ApplyAgentLayerResult {
  const result: ApplyAgentLayerResult = { written: [], deleted: [], errors: [], warnings: [] };
  const names = Object.keys(opts.agents);
  // NOTE: no unconditional mkdirSync — creating the target dir eagerly leaves
  // an empty all-default layer behind (extension session-start applied with no
  // `agents` section would otherwise materialize <repo>/.pi/agents for
  // nothing). The dir is created lazily below, only when a generated file is
  // actually written.

  const readBase = (targetPath: string, upstreamPath: string): string | undefined => {
    // Never throws (round-11 P1: an upstream path that is a DIRECTORY made
    // readFileSync throw EISDIR and aborted the whole layer render).
    const readText = (p: string): string | undefined => {
      try {
        if (existsSync(p) && statSync(p).isFile()) return readFileSync(p, "utf8");
      } catch { /* not readable — fall through */ }
      return undefined;
    };
    return readText(upstreamPath) ?? readText(targetPath);
  };
  const backupIfHandwritten = (name: string, targetPath: string, upstreamPath: string): boolean => {
    // Returns false when the adoption must NOT proceed (no working backup).
    if (!existsSync(targetPath)) return true;
    try {
      if (isGeneratedAgentFile(readFileSync(targetPath, "utf8"))) return true;
      let isUpstreamCopy = false;
      try {
        isUpstreamCopy =
          existsSync(upstreamPath) && readFileSync(targetPath, "utf8") === readFileSync(upstreamPath, "utf8");
      } catch { /* not comparable — treat as hand-written */ }
      if (isUpstreamCopy) return true;
      const bak = `${targetPath}.bak`;
      // Keep the .bak as the LATEST hand-written content: a stale backup
      // (v1) must not swallow a newer hand edit (v2) when the config is
      // lifted later — restore then brings back the newest user content
      // (round-11 P1: pre-existing .bak + newer hand-write lost v2).
      // A .bak path that is NOT a regular file (a directory, an unreadable
      // path) must not be silently skipped: taking over a hand-written
      // target without a working backup makes the adoption irreversible
      // (round-11 P1: .bak-as-directory lost the user's content).
      let bakOk = true;
      try {
        bakOk = !existsSync(bak) || statSync(bak).isFile();
      } catch { bakOk = false; }
      if (!bakOk) {
        result.errors.push(`${name}: the .bak path exists but is not a regular file — refusing to take over rendering (an unrecoverable overwrite)`);
        return false;
      }
      let bakStale = false;
      try {
        bakStale = existsSync(bak) && readFileSync(bak, "utf8") !== readFileSync(targetPath, "utf8");
      } catch { bakStale = false; }
      if (!existsSync(bak) || bakStale) {
        copyFileSync(targetPath, bak);
        result.warnings.push(`${name}: hand-written agent file detected; backed up as ${name}.md.bak before taking over rendering`);
      }
      return true;
    } catch {
      result.errors.push(`${name}: cannot read the target file to decide whether it is hand-written`);
      return false;
    }
  };

  for (const name of names) {
    const settings = opts.agents[name];
    const targetPath = join(opts.targetDir, `${name}.md`);
    const upstreamPath = join(opts.sourceDir, `${name}.md`);
    if (settings?.malformed) {
      // The entry named this agent but every field was invalid — keep the
      // last good render untouched (fail-safe; round-11 P1). Neither the
      // cleanup sweep nor a default-chain overlay may run over it.
      result.warnings.push(`${name}: invalid agents configuration; keeping the last render (fail-safe)`);
      continue;
    }
    const explicitlyConfigured = !!settings && settings.source !== "default";
    const wantsSlots = !!settings && settings.auto === false && settings.slots.length > 0;

    // (1) agent NOT configured in this layer → clean up any generated product
    // this layer used to hold (delete, or restore a prior backup).
    if (!explicitlyConfigured) {
      if (!existsSync(targetPath)) continue;
      try {
        if (isGeneratedAgentFile(readFileSync(targetPath, "utf8"))) {
          const bak = `${targetPath}.bak`;
          if (existsSync(bak)) {
            // The render erased a HAND-WRITTEN file earlier and backed it up
            // — restore it when the config is lifted, never leave the user's
            // content as an orphaned .bak.
            renameSync(bak, targetPath);
            result.warnings.push(`${name}: auto is on again; restoring the previously backed-up hand-written agent file`);
          } else if (opts.restoreDefault === true) {
            // Infrastructure layer (global): restore the upstream default file
            // instead of deleting — deleting would leave NO user-level agent
            // until the next install.
            if (existsSync(upstreamPath)) {
              copyFileSync(upstreamPath, targetPath);
              result.warnings.push(`${name}: configuration removed; restoring the upstream default agent file`);
            } else {
              // HARDENED: an unresolvable upstream used to fall through to the
              // delete branch, so "restore the default" silently became "remove
              // the only copy" — exactly the state that makes a required role
              // undispatchable. Keep the file and say why instead.
              result.warnings.push(`${name}: configuration removed but the upstream default is unresolvable (${upstreamPath}) — keeping the existing file rather than deleting the only copy`);
            }
          } else {
            rmSync(targetPath);
            result.deleted.push(name);
          }
        }
      } catch {
        result.errors.push(`${name}: cannot read/restore the rendered product`);
      }
      continue;
    }

    const base = readBase(targetPath, upstreamPath);
    if (base === undefined) {
      result.errors.push(`${name}: upstream file missing: ${upstreamPath}`);
      continue;
    }

    // (2) EXPLICIT auto:true → render the DEFAULT chain (marker + upstream
    // defaults) so this higher-precedence layer SHADOWS a lower layer's slot
    // render. Without this, project auto:true would leave the global auto:false
    // render in force, and the DEPLOYED model would contradict the effective
    // config (deployed != effective).
    if (!wantsSlots) {
      // The DEFAULT chain comes from the UPSTREAM file, never from a
      // hand-written target (round-5 P1: readBase's target fallback once
      // deployed the user's custom chain as if it were the built-in
      // default). No upstream copy ⇒ no trustworthy default: refuse rather
      // than fabricate one. The refusal comes BEFORE the backup — a failed
      // render must not strand an orphan .bak next to the untouched file
      // (round-7 P2).
      let chain: { model: string; fallback: string[] } | undefined;
      try {
        chain = extractFrontmatterChain(readFileSync(upstreamPath, "utf8"));
      } catch { chain = undefined; }
      if (!existsSync(upstreamPath) || chain === undefined) {
        result.errors.push(`${name}: the upstream default agent file is missing or unparseable — refusing to pass a hand-written chain off as the default chain`);
        continue;
      }
      if (!backupIfHandwritten(name, targetPath, upstreamPath)) continue;
      const rendered = replaceFrontmatterModels(base, { model: chain.model, fallbackModels: chain.fallback });
      if (rendered === undefined) {
        result.errors.push(`${name}: frontmatter parse failed (no --- block); not rewritten`);
        continue;
      }
      try {
        mkdirSync(opts.targetDir, { recursive: true });
        writeFileSync(targetPath, rendered, "utf8");
        result.written.push(name);
      } catch (e) {
        result.errors.push(`${name}: write failed: ${e instanceof Error ? e.message : String(e)}`);
      }
      continue;
    }

    // (3) auto:false + slots → validate, then render the slot chain.
    const slots = settings.slots;
    if (opts.validate !== false) {
      const v = validateSlots(opts.registry, slots);
      if (!v.ok) {
        result.errors.push(`${name}: ${v.reason}`);
        continue;
      }
      if (v.warning) result.warnings.push(`${name}: ${v.warning}`);
    }
    if (!backupIfHandwritten(name, targetPath, upstreamPath)) continue;
    const rendered = replaceFrontmatterModels(base, {
      model: slots[0]!,
      fallbackModels: slots.slice(1),
    });
    if (rendered === undefined) {
      result.errors.push(`${name}: frontmatter parse failed (no --- block); not rewritten`);
      continue;
    }
    try {
      mkdirSync(opts.targetDir, { recursive: true });
      writeFileSync(targetPath, rendered, "utf8");
      result.written.push(name);
    } catch (e) {
      result.errors.push(`${name}: write failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
  return result;
}
