#!/usr/bin/env node
/**
 * pi-review-gate postinstall installer (runs on `pi install`, `npm install`).
 *
 * pi packages natively load extensions + skills from the package itself, so
 * this installer ONLY handles what the pi package spec does not: the
 * sub-agents (loaded by pi-subagents from ~/.pi/agent/agents/), the git
 * hooks (installed per repo), and the COMPANION pi packages this extension
 * depends on at runtime (pi-subagents for the spawn-reviewer protocol,
 * pi-opencode-bridge for the opencode-go provider) — registered idempotently
 * via `pi install` so `pi install pi-review-gate` alone gives a working loop.
 *
 *   1. Copy agents/*.md → ~/.pi/agent/agents/  (idempotent, overwrite-owned)
 *   2. Register companion pi packages (pi-subagents / pi-opencode-bridge)
 *      into ~/.pi/agent/settings.json when missing (idempotent via `pi install`).
 *   3. If the current directory is a git repository, install the git hooks
 *      into it (the common local-dev case: `npm install` in this repo).
 *
 * Idempotent and fail-soft: a broken HOME or non-git cwd is not an error —
 * the extension still loads, and the README explains how to install hooks
 * per repo (`npx pi-review-gate-install-hooks` or the shipped script). A
 * missing `pi` CLI or a registration failure logs guidance instead of aborting.
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, statSync, readFileSync, writeFileSync, renameSync, unlinkSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const AGENT_DIR = join(homedir(), ".pi", "agent");
const AGENTS_DST = join(AGENT_DIR, "agents");
const PI_SETTINGS_PATH = join(AGENT_DIR, "settings.json");

// Agent basenames this package USED to ship but no longer does. An upgrade
// must delete their copies from AGENTS_DST: pi-subagents loads every *.md
// there, so a retired agent would otherwise keep running after the update.
const RETIRED_AGENTS = [
  "module-reviewer.md",
  "planner.md",
  "triage.md",
  "worker.md",
  "worker-readonly.md",
];

/**
 * Companion pi packages this extension needs at runtime. Each entry is a
 * `pi install`-style source spec; when missing from the user's
 * ~/.pi/agent/settings.json packages list the installer registers it (the
 * pi CLI fetches and installs the package itself). Registration is
 * idempotent by construction: `pi install` of an already-present package is a
 * no-op that keeps the existing entry.
 *
 * The list is the extension's WORKING PLATFORM: subagents (pi-subagents),
 * provider keys (pi-opencode-bridge / pi-anthropic-oauth), editor
 * integration (pi-vim, @narumitw/pi-lsp), MCP tooling (pi-mcp-adapter,
 * pi-web-access), notifications (pi-notify), and the hashline editor
 * (pi-hashline-edit-pro). Every entry is also pinned in package.json
 * dependencies so the whole platform resolves on `npm install` / `pi install`.
 */
const COMPANION_PACKAGES = [
  "npm:pi-subagents",
  "npm:pi-opencode-bridge",
  "npm:pi-anthropic-oauth",
  "npm:pi-mcp-adapter",
  "npm:pi-notify",
  "npm:pi-vim",
  "npm:pi-web-access",
  "npm:@narumitw/pi-lsp",
  "npm:pi-hashline-edit-pro"
];


function log(line) {
  process.stdout.write(`[pi-review-gate] ${line}\n`);
}

function isGitRepo(dir) {
  const r = spawnSync("git", ["rev-parse", "--show-toplevel"], {
    cwd: dir,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  return r.status === 0 && r.stdout.trim().length > 0;
}

function installAgents() {
  const srcDir = join(ROOT, "agents");
  if (!existsSync(srcDir)) {
    log("agents/ not found in package — skipping sub-agent install");
    return;
  }
  mkdirSync(AGENTS_DST, { recursive: true });
  let count = 0;
  for (const f of readdirSync(srcDir)) {
    if (!f.endsWith(".md")) continue;
    const src = join(srcDir, f);
    try {
      if (!statSync(src).isFile()) continue;
      const dst = join(AGENTS_DST, f);
      // Skip only files whose marker line starts with the EXACT generated
      // marker — the same prefix rule as lib/model-config.ts
      // isGeneratedAgentFile (first 8 lines, trimmed). A broader includes()
      // once froze files carrying a similar-but-foreign marker: skipped by
      // this copy, yet unmanaged by the renderer (round-3 P1).
      const MARKER = "# @generated by pi-review-gate models";
      // EXACT marker or marker + SPACE + suffix (retired render variant) —
      // never a concatenated continuation like models-other (round-11 P1).
      const isGenerated = (text) => text.split(/\r?\n/, 8).some((l) => {
        const t = l.trim();
        return t === MARKER || t.startsWith(`${MARKER} `);
      });
      const existing = existsSync(dst) ? readFileSync(dst, "utf8") : undefined;
      if (existing !== undefined && isGenerated(existing)) continue;
      copyFileSync(src, dst);
      count += 1;
    } catch (e) {
      log(`  ✗ could not install ${f}: ${e.message}`);
    }
  }
  log(`sub-agents installed (${count} files → ${AGENTS_DST})`);

  // Retired agents shipped by OLDER versions of this package must not linger:
  // pi-subagents loads every *.md in AGENTS_DST, so a leftover
  // module-reviewer.md / triage.md would keep running after an upgrade.
  let removed = 0;
  for (const f of RETIRED_AGENTS) {
    const dst = join(AGENTS_DST, f);
    if (!existsSync(dst)) continue;
    try {
      unlinkSync(dst);
      removed += 1;
      log(`  removed retired agent ${f}`);
    } catch (e) {
      log(`  ✗ could not remove retired agent ${f}: ${e.message}`);
    }
  }
  if (removed) log(`retired agents removed (${removed} → ${AGENTS_DST})`);
}

function installHooksHere() {
  if (!isGitRepo(process.cwd())) {
    log("current directory is not a git repo — skipping git-hook install");
    log(`per-repo hooks: run 'bash ${join(ROOT, "scripts", "install-git-hooks.sh")}' inside a repo`);
    return;
  }
  // A review snapshot is a linked worktree that SHARES .git/hooks with the real
  // checkout, so installing from inside one repoints the real repo's hooks at a
  // directory that is deleted with the round — breaking the L3 layer for every
  // later commit. The shell installer refuses too; this check keeps the reason
  // visible where the install is triggered.
  // All layouts carry an `rg-review-snap-` path segment (default
  // ~/.pi/review-snapshots/<repo-key>/rg-review-snap-<id>/…, repo-local
  // .pi/review-snapshots/rg-review-snap-<id>/… and the tmpdir fallback
  // <tmp>/rg-review-snap-<id>/…) — mirroring isReviewSnapshotPath.
  if (process.cwd().includes(`${sep}rg-review-snap-`)) {
    log("inside a review snapshot — refusing to install git hooks (.git/hooks is shared with the real checkout)");
    return;
  }
  log("current directory is a git repo — installing git hooks");
  const r = spawnSync("bash", [join(ROOT, "scripts", "install-git-hooks.sh")], {
    cwd: process.cwd(),
    stdio: "inherit",
  });
  if (r.status !== 0) {
    log(`  ✗ git-hook install exited ${r.status ?? "unknown"}`);
  }
}

/**
 * Write pi-subagents' fleet-inspector keybindings into the GLOBAL subagent
 * config (pi-subagents reads only <agentDir>/extensions/subagent/config.json;
 * there is no project-level file). The fleet inspector is where a subagent's
 * full session history can be scrolled; MacBooks have no PageUp/PageDown, so
 * the defaults bind vim-style Ctrl+b (up) / Ctrl+f, Ctrl+d (down) instead.
 *
 * Smart-merge, never clobber: the file is created when missing, the
 * fleetKeybindings field is added when absent (all other fields preserved),
 * and an EXISTING fleetKeybindings field is left completely alone — the
 * user's own bindings win. A file that does not parse, or is not a JSON
 * object (including an array), is skipped with a warning — never overwritten.
 */
const DEFAULT_FLEET_KEYBINDINGS = {
  fleetKeybindings: {
    pageUp: ["ctrl+b"],
    pageDown: ["ctrl+f", "ctrl+d"],
  },
};

function installFleetKeybindings() {
  const configPath = join(AGENT_DIR, "extensions", "subagent", "config.json");
  if (!existsSync(configPath)) {
    mkdirSync(dirname(configPath), { recursive: true });
    writeFileSync(configPath, `${JSON.stringify(DEFAULT_FLEET_KEYBINDINGS, null, "\t")}\n`, "utf8");
    log(`fleet keybindings written (${configPath})`);
    return;
  }
  let parsed;
  try {
    parsed = JSON.parse(readFileSync(configPath, "utf8"));
  } catch {
    log(`  ⚠ subagent config at ${configPath} is not valid JSON — leaving it untouched`);
    return;
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    log(`  ⚠ subagent config at ${configPath} is not a JSON object — leaving it untouched`);
    return;
  }
  if (parsed.fleetKeybindings !== undefined) {
    log("fleet keybindings already configured — keeping the user's bindings");
    return;
  }
  parsed.fleetKeybindings = DEFAULT_FLEET_KEYBINDINGS.fleetKeybindings;
  writeFileSync(configPath, `${JSON.stringify(parsed, null, "\t")}\n`, "utf8");
  log(`fleet keybindings merged into ${configPath}`);
}

/**
 * Register companion pi packages (pi-subagents, pi-opencode-bridge) that this
 * extension needs at runtime, so `pi install pi-review-gate` alone yields a
 * working review loop. Reads the user's ~/.pi/agent/settings.json packages
 * list: missing entries are registered via `pi install <spec>` (idempotent —
 * the CLI keeps an already-present package as-is). Fail-soft: a missing pi
 * CLI, unreadable settings, or a failed registration logs guidance instead of
 * failing the install. The `pi` CLI is located on PATH; when pi itself is not
 * on PATH (rare — the CLI ships with pi), the follow-up instructions tell the
 * user the exact command to run.
 */
function registerCompanions() {
  let settings;
  try {
    if (!existsSync(PI_SETTINGS_PATH)) {
      log("no ~/.pi/agent/settings.json — skipping companion package registration");
      log("  companion packages are only needed inside a pi agent; run 'pi install' to set up pi homes");
      return;
    }
    settings = JSON.parse(readFileSync(PI_SETTINGS_PATH, "utf8"));
  } catch (e) {
    log(`  ✗ could not read ${PI_SETTINGS_PATH}: ${e instanceof Error ? e.message : String(e)}`);
    return;
  }
  const packages = Array.isArray(settings?.packages) ? settings.packages : [];
  for (const spec of COMPANION_PACKAGES) {
    if (packages.includes(spec)) {
      log(`companion already registered: ${spec}`);
      continue;
    }
    log(`registering companion package: ${spec}`);
    const r = spawnSync("pi", ["install", spec], {
      stdio: "inherit",
      encoding: "utf8",
    });
    if (r.status !== 0) {
      log(`  ✗ could not register ${spec} — run 'pi install ${spec}' manually${r.error ? ` (${r.error.message})` : ""}`);
    }
  }
}
/**
 * USER REQUIREMENT — cost guard: the opencode-go provider bills per model
 * and ONLY deepseek-v4-flash is approved. Its models-store entry (a pi
 * provider cache) lists every billable model, so this prunes the cache to
 * flash alone on install. The code-level allowlist (lib/model-allowlist.ts
 * isModelAllowed) is the real backstop — this pruning only stops the
 * registry from even offering the expensive ids. Idempotent: a cache that
 * is already flash-only (or absent) is left untouched. Fail-soft: any IO
 * error logs guidance and never fails the install.
 */
function pruneOpenCodeGoModels() {
  const storePath = join(AGENT_DIR, "models-store.json");
  let raw;
  try {
    if (!existsSync(storePath)) return;
    raw = readFileSync(storePath, "utf8");
  } catch (e) {
    log(`  ✗ could not read ${storePath}: ${e.message} — leaving it untouched`);
    return;
  }
  let store;
  try {
    store = JSON.parse(raw);
  } catch (e) {
    log(`  ✗ ${storePath} is not valid JSON — leaving it untouched`);
    return;
  }
  if (typeof store !== "object" || store === null || Array.isArray(store)) return;
  const og = store["opencode-go"];
  if (!og || typeof og !== "object" || !Array.isArray(og.models)) return;
  const before = og.models.length;
  og.models = og.models.filter((m) => m && typeof m === "object" && m.id === "deepseek-v4-flash");
  if (og.models.length === before) return; // already flash-only
  try {
    // Keep one backup so a mistaken prune is reversible (never clobber an
    // existing one — the first prune's backup is the interesting one).
    if (!existsSync(`${storePath}.bak`)) copyFileSync(storePath, `${storePath}.bak`);
    const tmp = `${storePath}.tmp-${process.pid}`;
    writeFileSync(tmp, JSON.stringify(store, null, 1));
    renameSync(tmp, storePath);
    log(`pruned opencode-go models-store to deepseek-v4-flash only (${before} → ${og.models.length}; backup at ${storePath}.bak)`);
  } catch (e) {
    log(`  ✗ could not write pruned ${storePath}: ${e.message} — the code-level allowlist still guards model choice`);
  }
}

/**
 * GLOBAL-layer model-config render after the agents copy: reads the `agents`
 * section of ~/.pi/review-gate.json and renders the auto:false chains into
 * ~/.pi/agent/agents/*.md (project layer is NEVER touched from here — the
 * install cwd is not trustworthy).
 *
 * The model-config module is read as SOURCE and imported through a stripped
 * data URL rather than imported directly, for two reasons: (1) it is a
 * TypeScript module and Node refuses to type-strip anything under node_modules
 * (ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING), which is exactly where a
 * PUBLISHED install lives — stripping it ourselves keeps this step working
 * there too, so a published install DOES render the global layer from the
 * postinstall; (2) a failure here must never take down the agents copy /
 * companion registration / hook install (fail-soft, like the rest of the
 * installer). The EXTENSION renders both layers again at every session start
 * (`ensureModelLayersRendered`), so the render is covered even if this step is
 * skipped entirely.
 */
async function applyGlobalModelConfig() {
  try {
    const cfgPath = join(homedir(), ".pi", "review-gate.json");
    let raw;
    if (existsSync(cfgPath)) {
      try {
        const parsed = JSON.parse(readFileSync(cfgPath, "utf8"));
        if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("the top level is not a JSON object");
        raw = parsed;
      } catch (e) {
        // CORRUPT ≠ ABSENT: restoring defaults here would clobber the last
        // good rendered chains (the sweep runs when the section is genuinely
        // gone). Keep whatever is deployed and let the extension surface the
        // problem once the file is fixed.
        log(`  ⚠ global config is unreadable (${e instanceof Error ? e.message : String(e)}) — keeping the last rendered agent chains (fail-safe)`);
        return;
      }
    }
    if (raw && typeof raw === "object" && raw.agents !== undefined && (typeof raw.agents !== "object" || raw.agents === null || Array.isArray(raw.agents))) {
      // MALFORMED ≠ ABSENT: a non-object agents section would parse as "no
      // config" and the restoreDefault sweep would clobber the last rendered
      // chains — same fail-safe as the corrupt top level above.
      log(`  ⚠ the global config's agents section is not an object — keeping the last rendered agent chains (fail-safe)`);
      return;
    }
    const agents = raw && typeof raw === "object" ? raw.agents : undefined;
    const source = readFileSync(join(ROOT, "lib", "model-config.ts"), "utf8");
    const js = (await import("node:module")).stripTypeScriptTypes(source, { mode: "transform", sourceMap: false });
    const dataUrl = `data:text/javascript;base64,${Buffer.from(js, "utf8").toString("base64")}`;
    const { effectiveAgentsConfig, applyAgentConfigLayer, loadRegistry } = await import(dataUrl);
    const { map, diagnostics } = effectiveAgentsConfig(agents, undefined);
    for (const d of diagnostics) log(`  ⚠ model config: ${d}`);
    const res = applyAgentConfigLayer({
      agents: map,
      targetDir: AGENTS_DST,
      sourceDir: join(ROOT, "agents"),
      registry: loadRegistry(),
      restoreDefault: true,
    });
    for (const w of res.warnings) log(`  ⚠ ${w}`);
    for (const e of res.errors) log(`  ✗ ${e}`);
    if (res.written.length) log(`model config rendered (global layer): ${res.written.join(", ")}`);
    if (res.deleted.length) log(`model config restored to defaults (global layer): ${res.deleted.join(", ")}`);
  } catch (e) {
    log(`  · global model-config render skipped (${e instanceof Error ? e.message : String(e)})`);
    log("    the extension renders both layers at session start; nothing to do here.");
  }
}

try {
  installAgents();
  await applyGlobalModelConfig();
} catch (e) {
  log(`  ✗ agent install failed: ${e.message}`);
}

try {
  pruneOpenCodeGoModels();
} catch (e) {
  log(`  ✗ models-store prune failed: ${e.message}`);
}
try {
  registerCompanions();
} catch (e) {
  log(`  ✗ companion registration failed: ${e.message}`);
}
try {
  installHooksHere();
} catch (e) {
  log(`  ✗ hook install failed: ${e.message}`);
}
try {
  installFleetKeybindings();
} catch (e) {
  log(`  ✗ fleet keybindings install failed: ${e.message}`);
}
log("done (extension + skills load natively via the pi package manifest)");
